#!/usr/bin/env python2

import fileinput
import bz2
import os

MAX_DATA = 500L * 1000L * 1000L  # bytes

db_i, table_i, db_name, table_name = 0, 0, '', ''
old_filename, filename = '', ''
data_chunk = ''
of = None
i = 0

for line in fileinput.input():
    new_file = False
    i += 1

    # new database:
    if line.startswith(r'\connect '):
        db_i += 1
        table_i = 0
        db_name = line[9:].strip()
        table_name = 'structure'
        data_chunk = 0
        new_file = True

    # new data dump:
    if line.startswith(r'-- Data for Name: '):
        table_i += 1
        table_name = line.split(';')[0][18:]
        if len(table_name) > 50:
            table_name = table_name[:50] + '__'
        data_chunk = 1
        new_file = True

    # max size (data dumps can be big, split it):
    if data_chunk > 0 and i % 10000 == 0 and \
            os.stat(filename).st_size > MAX_DATA:
        data_chunk = data_chunk+1
        new_file = True

    if new_file:
        if of:
            of.close()
        if data_chunk > 0:
            filename = "%03d-%s-%04d-%s_d%d.sql.bz2" % (
                db_i, db_name, table_i, table_name, data_chunk)
        else:
            filename = "%03d-%s-%04d-%s.sql.bz2" % (
                db_i, db_name, table_i, table_name)
        print "-", filename
        of = bz2.BZ2File(filename, mode='w')

    if not of:
        continue

    of.write(line)
